// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDuq10vYtOP7gbn1J1hWINwm5KrBGvPsw',
    appId: '1:134130126302:web:69c853e96261064bbc614f',
    messagingSenderId: '134130126302',
    projectId: 'send-f16af',
    authDomain: 'send-f16af.firebaseapp.com',
    databaseURL: 'https://send-f16af-default-rtdb.firebaseio.com',
    storageBucket: 'send-f16af.appspot.com',
    measurementId: 'G-W950CZC9W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEFRA-e-inSKsjXJrTWhG8A9M8K4SHucA',
    appId: '1:134130126302:android:21e5c81a283cf127bc614f',
    messagingSenderId: '134130126302',
    projectId: 'send-f16af',
    databaseURL: 'https://send-f16af-default-rtdb.firebaseio.com',
    storageBucket: 'send-f16af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZif7ptlQH5kSHI56FSnVxmuiB3LaKx_U',
    appId: '1:134130126302:ios:c00536127a8349cdbc614f',
    messagingSenderId: '134130126302',
    projectId: 'send-f16af',
    databaseURL: 'https://send-f16af-default-rtdb.firebaseio.com',
    storageBucket: 'send-f16af.appspot.com',
    iosBundleId: 'com.example.sendhome',
  );
}
